-- MySQL Script generated by MySQL Workbench
-- Wed Aug 31 14:27:51 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Category` ;

CREATE TABLE IF NOT EXISTS `Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `Category_Name` VARCHAR(45) NULL,
  `Category_ParentID` INT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Staff` ;

CREATE TABLE IF NOT EXISTS `Staff` (
  `idStaff` INT NOT NULL AUTO_INCREMENT,
  `Staff_FirstName` VARCHAR(45) NULL,
  `Staff_LastName` VARCHAR(45) NULL,
  `Staff_Username` VARCHAR(45) NULL,
  `Staff_Password` VARCHAR(45) NULL,
  `Staff_PhoneNumber` VARCHAR(16) NULL,
  `Staff_LastLogin` TIMESTAMP NULL,
  PRIMARY KEY (`idStaff`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Product` ;

CREATE TABLE IF NOT EXISTS `Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `Product_Name` VARCHAR(100) NULL,
  `Product_ShortDesc` VARCHAR(200) NULL,
  `Product_LongDesc` TEXT NULL,
  `Product_Stock` VARCHAR(45) NULL,
  `Product_Price` VARCHAR(45) NULL,
  `Product_Wight` FLOAT NULL,
  `Product_Image` VARCHAR(45) NULL,
  `Product_Location` VARCHAR(200) NULL,
  `Product_UpdateTime` TIMESTAMP NULL,
  `Category_idCategory` INT NOT NULL,
  `Staff_idStaff` INT NOT NULL,
  PRIMARY KEY (`idProduct`, `Staff_idStaff`),
  INDEX `fk_Product_Category1_idx` (`Category_idCategory` ASC),
  INDEX `fk_Product_Staff1_idx` (`Staff_idStaff` ASC),
  CONSTRAINT `fk_Product_Category1`
    FOREIGN KEY (`Category_idCategory`)
    REFERENCES `Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Staff1`
    FOREIGN KEY (`Staff_idStaff`)
    REFERENCES `Staff` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Customer` ;

CREATE TABLE IF NOT EXISTS `Customer` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `Customer_Username` VARCHAR(30) NULL COMMENT '	',
  `Customer_Password` VARCHAR(30) NULL,
  `Customer_Email` VARCHAR(45) NULL,
  `Customer_EmailVerfied` VARCHAR(45) NULL,
  `Customer_Firstname` VARCHAR(30) NULL,
  `Customer_Lastname` VARCHAR(30) NULL,
  `Customer_PhoneNumber` VARCHAR(15) NULL,
  `Customer_Fax` VARCHAR(16) NULL,
  `Customer_Address` VARCHAR(45) NULL,
  `Customer_Address2` VARCHAR(45) NULL,
  `Customer_Gender` VARCHAR(6) NULL,
  `Customer_BirthDate` DATE NULL,
  `Customer_Country` VARCHAR(30) NULL,
  `Customer_State` VARCHAR(30) NULL COMMENT '					',
  `Customer_City` VARCHAR(30) NULL,
  `Customer_Zip` VARCHAR(12) NULL,
  `Customer_RegistrationDate` TIMESTAMP NULL,
  `Customer_LastLoginDate` TIMESTAMP NULL,
  `Customer_LastLoginIP` VARCHAR(16) NULL,
  PRIMARY KEY (`idCustomer`))
ENGINE = InnoDB
AUTO_INCREMENT = 1000;


-- -----------------------------------------------------
-- Table `Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Comment` ;

CREATE TABLE IF NOT EXISTS `Comment` (
  `idComment` INT NOT NULL AUTO_INCREMENT,
  `Comment_Msg` VARCHAR(300) NULL,
  `Comment_LastModifyDate` TIMESTAMP NULL,
  `Customer_idCustomer` INT NOT NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`idComment`, `Customer_idCustomer`, `Product_idProduct`),
  INDEX `fk_Comment_Customer_idx` (`Customer_idCustomer` ASC),
  INDEX `fk_Comment_Product1_idx` (`Product_idProduct` ASC),
  CONSTRAINT `fk_Comment_Customer`
    FOREIGN KEY (`Customer_idCustomer`)
    REFERENCES `Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rating` ;

CREATE TABLE IF NOT EXISTS `Rating` (
  `idRating` INT NOT NULL AUTO_INCREMENT,
  `Rating_Value` VARCHAR(45) NULL,
  `Rating_Date` TIMESTAMP NULL,
  `Customer_idCustomer` INT NOT NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`idRating`, `Customer_idCustomer`, `Product_idProduct`),
  INDEX `fk_Rating_Customer1_idx` (`Customer_idCustomer` ASC),
  INDEX `fk_Rating_Product1_idx` (`Product_idProduct` ASC),
  CONSTRAINT `fk_Rating_Customer1`
    FOREIGN KEY (`Customer_idCustomer`)
    REFERENCES `Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rating_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Order` ;

CREATE TABLE IF NOT EXISTS `Order` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `Customer_idCustomer` INT NOT NULL,
  `Product_idProduct` INT NOT NULL,
  `Product_Staff_idStaff` INT NOT NULL,
  `Order_Amount` FLOAT NULL,
  `Order_ShipName` VARCHAR(100) NULL,
  `Order_ShipAddress` VARCHAR(100) NULL,
  `Order_Country` VARCHAR(45) NULL,
  `Order_State` VARCHAR(45) NULL,
  `Order_City` VARCHAR(45) NULL,
  `Order_Zip` VARCHAR(10) NULL,
  `Order_Phone` VARCHAR(12) NULL,
  `Order_Fax` VARCHAR(12) NULL,
  `Order_Tax` FLOAT NULL,
  `Order_Email` VARCHAR(45) NULL,
  `Order_Date` TIMESTAMP NULL,
  `Order_Shipped` TINYINT NULL,
  `Order_TrackingNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`idOrder`, `Customer_idCustomer`, `Product_idProduct`, `Product_Staff_idStaff`),
  INDEX `fk_Order_Customer1_idx` (`Customer_idCustomer` ASC),
  INDEX `fk_Order_Product1_idx` (`Product_idProduct` ASC, `Product_Staff_idStaff` ASC),
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`Customer_idCustomer`)
    REFERENCES `Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Product1`
    FOREIGN KEY (`Product_idProduct` , `Product_Staff_idStaff`)
    REFERENCES `Product` (`idProduct` , `Staff_idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Staff_Modify_Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Staff_Modify_Product` ;

CREATE TABLE IF NOT EXISTS `Staff_Modify_Product` (
  `Staff_idStaff` INT NOT NULL,
  `Product_idProduct` INT NOT NULL,
  `Product_Staff_idStaff` INT NOT NULL,
  `Modification_Date` TIMESTAMP NULL,
  `Modification_comment` VARCHAR(100) NULL,
  PRIMARY KEY (`Staff_idStaff`, `Product_idProduct`, `Product_Staff_idStaff`),
  INDEX `fk_Staff_has_Product_Product1_idx` (`Product_idProduct` ASC, `Product_Staff_idStaff` ASC),
  INDEX `fk_Staff_has_Product_Staff1_idx` (`Staff_idStaff` ASC),
  CONSTRAINT `fk_Staff_has_Product_Staff1`
    FOREIGN KEY (`Staff_idStaff`)
    REFERENCES `Staff` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Staff_has_Product_Product1`
    FOREIGN KEY (`Product_idProduct` , `Product_Staff_idStaff`)
    REFERENCES `Product` (`idProduct` , `Staff_idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
